version: '3.8'

services:
  mysql:
    container_name: 'mysql'
    image: mysql:5.7.32
    environment:
      MYSQL_DATABASE: eatmod
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: ''
      PMA_HOSTS: mysql